//! Egress policy → nftables rule compiler.
//!
//! The allowlist compiles to nftables verdict maps. Tests are
//! table-driven: allowlist spec → expected nftables/eBPF program.
//!
//! This module turns an [`EgressPolicy`] into a list of nftables rule
//! strings that, when applied in a per-VM netns, enforce default-deny
//! egress with the allowlist. Pure string-building — host-agnostic and
//! unit-testable without nft or root.

use crate::egress::{EgressPolicy, EgressRule, Proto};
use std::net::IpAddr;
use thiserror::Error;

#[derive(Debug, Error, PartialEq, Eq)]
pub enum NftCompileError {
    #[error("invalid nft chain name {chain:?}: {reason}")]
    InvalidChain { chain: String, reason: &'static str },
    #[error("invalid CIDR/IP {cidr:?}: {reason}")]
    InvalidCidr { cidr: String, reason: &'static str },
    #[error("invalid protocol: {0}")]
    InvalidProto(&'static str),
}

/// Compile a policy into a list of nftables `add rule` statements.
///
/// The generated rules assume a chain named `vmm_egress` in an `inet`
/// table `vmm`, with a default-drop policy. Each allow rule emits one
/// `add rule` that accepts matching traffic; the final drop is the chain's
/// policy (not emitted as a rule).
pub fn compile_to_nft(policy: &EgressPolicy, chain: &str) -> Vec<String> {
    try_compile_to_nft(policy, chain).expect("valid nft egress policy and chain")
}

/// Checked variant of [`compile_to_nft`] that rejects invalid inputs before
/// formatting nft command strings.
pub fn try_compile_to_nft(
    policy: &EgressPolicy,
    chain: &str,
) -> Result<Vec<String>, NftCompileError> {
    validate_chain_name(chain)?;
    let mut rules = Vec::with_capacity(policy.rules.len());
    for r in &policy.rules {
        validate_rule(r)?;
        rules.push(format!("add rule inet vmm {chain} {}", render_rule(r)));
    }
    Ok(rules)
}

/// Render a single rule as its nft match-expr, e.g.
/// `ip daddr 10.0.0.0/8 tcp dport 443 accept`.
fn render_rule(r: &EgressRule) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("ip daddr {}", r.cidr));
    if r.port != 0 {
        let proto_str = match r.proto {
            Proto::Tcp => "tcp",
            Proto::Udp => "udp",
            Proto::Any => "tcp", // any → emit two rules; here we pick tcp
        };
        parts.push(format!("{proto_str} dport {} accept", r.port));
    } else {
        let verdict = match r.proto {
            Proto::Tcp => "tcp",
            Proto::Udp => "udp",
            Proto::Any => "",
        };
        if verdict.is_empty() {
            parts.push("accept".into());
        } else {
            parts.push(format!("meta l4proto {verdict} accept"));
        }
    }
    parts.join(" ")
}

/// Compile a full nftables table+chain setup for a per-VM netns.
///
/// Emits: `add table`, `add chain` (with default-drop policy), an always-on
/// stateful reply accept rule, and the allow rules. Apply with `nft -f -`
/// inside the VM's netns.
pub fn compile_table(policy: &EgressPolicy) -> Vec<String> {
    try_compile_table(policy).expect("valid nft egress policy")
}

/// Checked variant of [`compile_table`] that rejects invalid allowlist rules
/// before formatting nft command strings.
pub fn try_compile_table(policy: &EgressPolicy) -> Result<Vec<String>, NftCompileError> {
    let mut out = Vec::new();
    out.push("add table inet vmm".into());
    // Enforce on the `forward` hook: the guest's traffic is routed (forwarded)
    // through the per-VM netns from the tap to the uplink, so it traverses the
    // forward path, not the netns's local `output` path. Filtering on `output`
    // would only see traffic generated by processes inside the netns and let the
    // guest's forwarded egress bypass the allowlist entirely.
    out.push(
        "add chain inet vmm vmm_egress { type filter hook forward priority 0; policy drop; }"
            .into(),
    );
    out.push("add rule inet vmm vmm_egress ct state established,related accept".into());
    out.extend(try_compile_to_nft(policy, "vmm_egress")?);
    Ok(out)
}

pub fn validate_chain_name(chain: &str) -> Result<(), NftCompileError> {
    let mut chars = chain.chars();
    let first = chars.next().ok_or_else(|| NftCompileError::InvalidChain {
        chain: chain.to_string(),
        reason: "chain name must not be empty",
    })?;

    if !(first.is_ascii_alphabetic() || first == '_') {
        return Err(NftCompileError::InvalidChain {
            chain: chain.to_string(),
            reason: "chain name must start with an ASCII letter or underscore",
        });
    }

    if !chars.all(|c| c.is_ascii_alphanumeric() || c == '_') {
        return Err(NftCompileError::InvalidChain {
            chain: chain.to_string(),
            reason: "chain name may only contain ASCII letters, digits, and underscores",
        });
    }

    Ok(())
}

pub fn validate_cidr_or_ip(cidr: &str) -> Result<(), NftCompileError> {
    let (addr, prefix) = match cidr.split_once('/') {
        Some((addr, prefix)) if !prefix.contains('/') => (addr, Some(prefix)),
        Some(_) => {
            return Err(NftCompileError::InvalidCidr {
                cidr: cidr.to_string(),
                reason: "CIDR must contain a single prefix separator",
            });
        }
        None => (cidr, None),
    };

    let addr = addr
        .parse::<IpAddr>()
        .map_err(|_| NftCompileError::InvalidCidr {
            cidr: cidr.to_string(),
            reason: "address must be a valid IPv4 or IPv6 address",
        })?;

    if let Some(prefix) = prefix {
        let prefix_len = prefix
            .parse::<u8>()
            .map_err(|_| NftCompileError::InvalidCidr {
                cidr: cidr.to_string(),
                reason: "prefix length must be numeric",
            })?;
        let max_prefix = if addr.is_ipv4() { 32 } else { 128 };
        if prefix_len > max_prefix {
            return Err(NftCompileError::InvalidCidr {
                cidr: cidr.to_string(),
                reason: "prefix length exceeds address-family width",
            });
        }
    }

    Ok(())
}

fn validate_rule(rule: &EgressRule) -> Result<(), NftCompileError> {
    validate_cidr_or_ip(&rule.cidr)?;
    validate_proto(rule.proto)?;
    Ok(())
}

fn validate_proto(proto: Proto) -> Result<(), NftCompileError> {
    match proto {
        Proto::Tcp | Proto::Udp | Proto::Any => Ok(()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::egress::EgressRule;

    #[test]
    fn deny_all_emits_table_chain_and_stateful_reply_rule() {
        let p = EgressPolicy::deny_all();
        let t = compile_table(&p);
        assert_eq!(t.len(), 3); // table + chain + stateful reply rule, no allow rules
        assert!(t[0].starts_with("add table"));
        assert!(t[1].contains("policy drop"));
        assert!(t[2].contains("ct state established,related accept"));
    }

    #[test]
    fn tcp_port_rule_renders_dport() {
        let mut p = EgressPolicy::deny_all();
        p.add(EgressRule {
            cidr: "10.0.0.0/8".into(),
            port: 443,
            proto: Proto::Tcp,
        });
        let rules = compile_to_nft(&p, "vmm_egress");
        assert_eq!(rules.len(), 1);
        assert!(rules[0].contains("ip daddr 10.0.0.0/8"));
        assert!(rules[0].contains("tcp dport 443 accept"));
    }

    #[test]
    fn any_proto_any_port_renders_bare_accept() {
        let p = EgressPolicy::allow_all();
        let rules = compile_to_nft(&p, "vmm_egress");
        assert_eq!(rules.len(), 1);
        assert!(rules[0].ends_with("accept"));
    }

    #[test]
    fn udp_rule_renders_udp_dport() {
        let mut p = EgressPolicy::deny_all();
        p.add(EgressRule {
            cidr: "8.8.8.8/32".into(),
            port: 53,
            proto: Proto::Udp,
        });
        let rules = compile_to_nft(&p, "vmm_egress");
        assert!(rules[0].contains("udp dport 53 accept"));
    }

    #[test]
    fn full_table_has_correct_shape() {
        let mut p = EgressPolicy::deny_all();
        p.add(EgressRule {
            cidr: "0.0.0.0/0".into(),
            port: 80,
            proto: Proto::Tcp,
        });
        let t = compile_table(&p);
        assert!(t[0].starts_with("add table inet vmm"));
        assert!(t[1].contains("hook forward"));
        assert!(t[1].contains("policy drop"));
        assert!(t[2].contains("ct state established,related accept"));
        assert!(t[3].contains("tcp dport 80 accept"));
    }

    #[test]
    fn checked_compile_rejects_injected_chain() {
        let p = EgressPolicy::deny_all();
        let err = try_compile_to_nft(&p, "vmm_egress\nflush ruleset").unwrap_err();
        assert!(matches!(err, NftCompileError::InvalidChain { .. }));
    }

    #[test]
    fn checked_compile_rejects_injected_cidr() {
        let mut p = EgressPolicy::deny_all();
        p.add(EgressRule {
            cidr: "10.0.0.0/8 accept; flush ruleset".into(),
            port: 443,
            proto: Proto::Tcp,
        });
        let err = try_compile_to_nft(&p, "vmm_egress").unwrap_err();
        assert!(matches!(err, NftCompileError::InvalidCidr { .. }));
    }

    #[test]
    fn checked_compile_accepts_valid_ip_and_cidr_inputs() {
        assert!(validate_cidr_or_ip("8.8.8.8").is_ok());
        assert!(validate_cidr_or_ip("10.0.0.0/8").is_ok());
        assert!(validate_cidr_or_ip("2001:db8::/32").is_ok());
        assert!(validate_cidr_or_ip("10.0.0.0/33").is_err());
    }
}
